on load:
    add "&a+&7 Shulker Inventory: By pressing your offhand swap key you" and "&7can open up a second inventory with 9 slots" and "&7that keeps on death" to {_lore::*}
    add "&a+&7 Hard Shell: You have natural armor" to {_lore::*}
    add "&c-&7 Unwieldy: You cannot use shields" to {_lore::*}
    add "&c-&7 Heavy Shell: You loose hunger faster" to {_lore::*}
    registerOrigin("Shulk", "5", 20, shulker shell of unbreaking 1 named "&5Shulk" with lore {_lore::*} with hide enchants item flag)

on unload:
    unregisterOrigin("Shulk")

on right click:
    if {zevorigins.origin.player::%player's uuid%} is "Shulk":
        if player's offhand tool is shield:
            drop player's offhand tool at player
            set player's offhand tool to air
            send action bar "&cShulks cannot use shields"
        if player's tool is shield:
            drop player's tool at player
            set player's tool to air
            send action bar "&cShulks cannot use shields"
            
on swap hand items:
    if {zevorigins.origin.player::%player's uuid%} is "Shulk":
        cancel event
        set {_shulkinv} to dropper inventory named colored "&5Shulk Inventory"
        add {zevorigins.origin.shulk.shulkinventory.%player's uuid%::*} to {_shulkinv}
        remove all gray stained glass pane named "&fAir Placeholder" with lore "&cIf you're seeing this contact zevcraft on discord because there is a bug" from {_shulkinv}
        delete {zevorigins.origin.shulk.shulkinventory.%player's uuid%::*}
        open {_shulkinv} to player
        
on inventory close:
    if {zevorigins.origin.player::%player's uuid%} is "Shulk":
        name of event-inventory is "&5Shulk Inventory":
            add 5184 gray stained glass pane named "&fAir Placeholder" with lore "&cIf you're seeing this contact zevcraft on discord because there is a bug" to event-inventory
            loop items in event-inventory:
                add loop-item to {zevorigins.origin.shulk.shulkinventory.%player's uuid%::*}

every 1 second:
    loop all players where [{zevorigins.origin.player::%input's uuid%} is "Shulk"]:
        apply hunger 1 without any particles whilst hiding the potion icon to loop-player for 3 seconds replacing the existing effect
        set loop-player's armor attribute to 6